
version: 2
jobs:
  build-job:
    working_directory: ~/repo
    docker:
    - image: circleci/node:8.10
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: yarn build
    - persist_to_workspace:
        root: ~/repo
        paths:
        - build
        - node_modules
  deploy-job:
    working_directory: ~/repo
    docker:
    - image: circleci/node:8.10
    steps:
    - checkout
    - attach_workspace:
        at: ~/repo
    - run: git config --global user.email "$GH_EMAIL"
    - run: git config --global user.name "$GH_NAME"
    - run: npx gh-pages -d build
workflows:
  version: 2
  build-deploy:
    jobs:
    - build-job:
        filters:
          branches:
            ignore: gh-pages
    - deploy-job:
        requires:
        - build-job
        filters:
          branches:
            only: master
